### ISSUE TITLE
what's the near and velsmooth function meaning?

### ISSUE THREAD

**Issue by xichaoqiang** [liugele/mFAST#1]
Hello,

Thanks for sharing this interesting package.

When I run the code, I meet an error with near and velsmooth functions.

![image](https://user-images.githubusercontent.com/30900789/163949729-790218f3-df77-4c3a-8b11-cc134541241f.png)

![image](https://user-images.githubusercontent.com/30900789/163954780-0416dbd4-e7c5-43b2-9a6a-ad35d4b6dac9.png)

Can you share these functions with me?

Best reagrds,
Xi

**Comment by liugele** [comment]
sorry for missing that function. please see the attachment.
thank for downloading  the matlab toolbox.
















At 2022-04-19 15:32:30, "xichaoqiang" ***@***.***> wrote:

Hello,

Thanks for sharing this interesting package.

When I run the code, I meet an error with near function.

Can you share this function with me?

Best reagrds,
Xi

**Comment by xichaoqiang** [comment]
Thanks for you kindly reply.
